# Generated by Django 4.0.4 on 2022-05-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(default=0, verbose_name='Отметка')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mark', verbose_name='Отметки'),
        ),
    ]
