# Generated by Django 4.0.4 on 2022-05-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mark_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('classroom', models.PositiveSmallIntegerField(default=0, verbose_name='Аудитория')),
                ('day', models.PositiveSmallIntegerField(default=0, verbose_name='День недели')),
                ('bell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bell', verbose_name='Звонок')),
                ('dicipline', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dicipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(default=0, verbose_name='Отметка')),
                ('exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='main.exam', verbose_name='Отметки')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_marks', to='main.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
            },
        ),
    ]
