# Generated by Django 4.0.4 on 2022-05-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_student_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('surname', 'name', 'second_name'), 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/students/', verbose_name='Фото'),
        ),
    ]
