# Generated by Django 4.0.4 on 2022-05-31 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_missings'),
    ]

    operations = [
        migrations.AddField(
            model_name='missings',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='missings',
            name='dicipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missings', to='main.dicipline', verbose_name='Пропуски'),
        ),
        migrations.AddField(
            model_name='missings',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missings', to='main.student', verbose_name='Пропуски'),
        ),
    ]
