# Generated by Django 4.0.4 on 2022-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_missings_date_missings_dicipline_missings_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missings',
            name='hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
