# Generated by Django 4.0.4 on 2022-06-06 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
