# Generated by Django 4.0.4 on 2022-06-07 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='main.exam', verbose_name='Отметки'),
        ),
    ]
