# Generated by Django 4.0.4 on 2022-05-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.PositiveSmallIntegerField(default=0, verbose_name='№: ')),
                ('start', models.TimeField()),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.CreateModel(
            name='Dicipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название: ')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер: ')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет: ')),
                ('specialisation', models.CharField(max_length=200, verbose_name='Специальность: ')),
                ('course', models.PositiveSmallIntegerField(default=0, verbose_name='Курс: ')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя: ')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество: ')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия: ')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фото: ')),
                ('rang', models.CharField(max_length=200, verbose_name='Должность: ')),
                ('email', models.EmailField(max_length=200, verbose_name='Электронная почта: ')),
                ('diciplines', models.ManyToManyField(to='main.dicipline', verbose_name='Дисциплины: ')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя: ')),
                ('second_name', models.CharField(max_length=50, verbose_name='Отчество: ')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия: ')),
                ('photo', models.ImageField(upload_to='students/', verbose_name='Фото: ')),
                ('rating', models.FloatField(verbose_name='Рейтинг: ')),
                ('number', models.PositiveBigIntegerField(default=0, verbose_name='Студенческий билет: ')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Номер группы: ')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.PositiveSmallIntegerField(default=0, verbose_name='Аудитория: ')),
                ('week', models.PositiveSmallIntegerField(default=0, verbose_name='Неделя: ')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='№: ')),
                ('bell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bell', verbose_name='Звонок')),
                ('dicipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dicipline', verbose_name='Дисциплина: ')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Расписание: ')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher', verbose_name='Преподаватель: ')),
            ],
            options={
                'verbose_name': 'Расписание',
            },
        ),
    ]
