# Generated by Django 4.0.4 on 2022-05-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='number',
        ),
        migrations.AlterField(
            model_name='dicipline',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.CharField(max_length=200, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=6, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialisation',
            field=models.CharField(max_length=200, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dicipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dicipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Неделя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Студенческий билет'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rating',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='diciplines',
            field=models.ManyToManyField(to='main.dicipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='teachers/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rang',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
