# Generated by Django 4.0.4 on 2022-05-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_schedule_number_alter_dicipline_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bell',
            name='duration',
            field=models.DurationField(verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='bell',
            name='pair',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='bell',
            name='start',
            field=models.TimeField(verbose_name='Начало'),
        ),
    ]
