# Generated by Django 4.0.4 on 2022-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schedule_options_alter_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='День недели'),
        ),
    ]
