# Generated by Django 4.0.4 on 2022-05-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mark_alter_schedule_group_schedule_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='marks',
        ),
        migrations.AddField(
            model_name='mark',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='main.schedule', verbose_name='Отметки'),
        ),
    ]
