# Generated by Django 4.0.4 on 2022-05-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_exammark_options_alter_exam_dicipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/teachers/', verbose_name='Фото'),
        ),
    ]
