# Generated by Django 4.0.4 on 2022-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_mark_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='pair_type',
            field=models.CharField(default='', max_length=50, verbose_name='Тип'),
        ),
    ]
