# Generated by Django 4.0.4 on 2022-05-31 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_schedule_pair_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exammark',
            options={'verbose_name': 'Экзаменационная отметка', 'verbose_name_plural': 'Экзаменационные отметки'},
        ),
        migrations.RemoveField(
            model_name='mark',
            name='schedule',
        ),
        migrations.AddField(
            model_name='mark',
            name='dicipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='main.dicipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pair_type',
            field=models.CharField(choices=[('лк', 'Лекция'), ('пз', 'Практическое занятие'), ('лр', 'Лабораторная работа')], default='', max_length=50, verbose_name='Тип'),
        ),
    ]
