# Generated by Django 4.0.4 on 2022-05-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_exammark_options_remove_mark_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Часы пропусков',
            },
        ),
    ]
