# Generated by Django 4.0.4 on 2022-06-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_exammark_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rating',
        ),
    ]
