run:
	python3 manage.py runserver 0.0.0.0:8000

makemigrations:
	python3 manage.py makemigrations main

migrate:
	python3 manage.py migrate
	
db:
	python3 manage.py makemigrations main
	python3 manage.py migrate

user:
	python3 manage.py createsuperuser